export type PricingPackage = {
  name: string
  price: string
  renewal?: string
  period?: string
  features: string[]
  description: string
  popular: boolean
}

// Pricing packages per service slug
export const servicePricing: Record<string, PricingPackage[]> = {
  'jasa-pembuatan-company-profile': [
    {
      name: 'Paket UMKM',
      price: 'Rp 1.250.000',
      renewal: 'Perpanjangan Rp 500.000/thn',
      features: [
        '3 Halaman (Beranda, Tentang, Kontak)',
        '1x Revisi',
        '1 Email Bisnis (nama@domain.id)',
        '1 GB SSD Hosting',
        'Gratis Maintenance 1 Tahun',
        'Gratis Domain .my.id / .biz.id',
        'SSL Certificate Selamanya',
        'Mobile Responsive',
        'SEO On-Page Basic',
        'Integrasi WhatsApp',
      ],
      description: 'Cocok untuk UMKM dan bisnis kecil yang baru mulai membangun kehadiran online.',
      popular: false,
    },
    {
      name: 'Paket Bisnis',
      price: 'Rp 2.350.000',
      renewal: 'Perpanjangan Rp 750.000/thn',
      features: [
        '8 Halaman (Profil, Layanan, Portfolio, Blog, dll)',
        '3x Revisi',
        '5 Email Bisnis',
        '5 GB SSD Hosting',
        'Gratis Maintenance 1 Tahun',
        'Gratis Domain .com',
        'SSL Certificate Selamanya',
        'Mobile Responsive',
        'SEO On-Page + Schema Markup',
        'Google Maps & WhatsApp Floating',
        'Form Kontak',
        'Copywriting Halaman Utama',
      ],
      description: 'Pilihan terbaik untuk perusahaan menengah yang ingin tampil profesional di Google.',
      popular: true,
    },
    {
      name: 'Paket Corporate',
      price: 'Rp 3.250.000',
      renewal: 'Perpanjangan Rp 1.000.000/thn',
      features: [
        '15+ Halaman Custom',
        '5x Revisi + Konsultasi Desain',
        'Unlimited Email Bisnis',
        'Unlimited SSD Hosting',
        'Gratis Maintenance 1 Tahun',
        'Gratis Domain .com / .co.id',
        'SSL Certificate Selamanya',
        'Mobile Responsive + AMP',
        'SEO Advanced + Sitemap + Schema',
        'Blog / Artikel System',
        'Copywriting Seluruh Halaman',
        'Multi-Language Ready',
        'Analytics Dashboard',
      ],
      description: 'Untuk perusahaan besar dan korporasi yang membutuhkan website lengkap premium.',
      popular: false,
    },
  ],
  'jasa-pembuatan-landing-page': [
    {
      name: 'Paket Starter',
      price: 'Rp 600.000',
      features: [
        '1 Halaman Landing Page',
        'Desain Modern & Responsif',
        'Copywriting Dasar',
        'Form Lead Generation',
        'Tombol WhatsApp',
        'Gratis Domain & Hosting 1 Tahun',
        'SSL Certificate',
        'SEO Basic',
        '1x Revisi',
      ],
      description: 'Landing page sederhana untuk promosi produk dan lead generation.',
      popular: false,
    },
    {
      name: 'Paket Profesional',
      price: 'Rp 1.500.000',
      features: [
        'Landing Page Multi-Section',
        'Copywriting Persuasif Profesional',
        'Integrasi Meta Pixel & Google Analytics',
        'Form + WhatsApp Redirect',
        'Gratis Domain .com & Hosting',
        'SSL Certificate',
        'SEO Friendly + Schema',
        'Loading Super Cepat',
        '3x Revisi',
        'A/B Testing Ready',
      ],
      description: 'Landing page lengkap dengan copywriting profesional dan integrasi ads pixel.',
      popular: true,
    },
    {
      name: 'Paket Custom',
      price: 'Hubungi Kami',
      features: [
        'Multi-Page Landing',
        'Copywriting Full Custom',
        'Integrasi CRM / Email Marketing',
        'Custom Animasi & Interaksi',
        'Multi-Variant / A-B Testing',
        'Konsultasi Strategi Konversi',
        'Unlimited Revisi',
        'Priority Support',
      ],
      description: 'Untuk kebutuhan khusus, multi-page, atau integrasi kompleks.',
      popular: false,
    },
  ],
  'jasa-pembuatan-toko-online': [
    {
      name: 'Starter',
      price: 'Rp 1.500.000',
      features: [
        'Hingga 50 Produk',
        'Desain Mobile-First',
        'Checkout + Payment Gateway',
        'Cek Ongkir Otomatis (JNE, J&T, SiCepat)',
        'Dashboard Admin',
        'Gratis Domain .com & Hosting',
        'SSL Certificate',
        'SEO Basic',
        'Support 30 Hari',
      ],
      description: 'Cocok untuk bisnis kecil yang baru mulai jualan online.',
      popular: false,
    },
    {
      name: 'Professional',
      price: 'Rp 3.500.000',
      features: [
        'Produk Tidak Terbatas',
        'Desain Custom Sesuai Brand',
        'Multi Payment Gateway',
        'Cek Ongkir 15+ Kurir',
        'Dashboard Admin Lengkap',
        'Kupon & Flash Sale',
        'Blog / Artikel',
        'Gratis Domain .com & Hosting',
        'SEO Advanced + Schema',
        'Support 60 Hari',
        'Training Admin',
      ],
      description: 'Untuk bisnis yang serius jualan online dan ingin tampil profesional.',
      popular: true,
    },
    {
      name: 'Enterprise',
      price: 'Hubungi Kami',
      features: [
        'Semua Fitur Professional',
        'Desain Full Custom',
        'Multi-Bahasa',
        'Integrasi Marketplace',
        'Integrasi Accounting',
        'Custom Reporting',
        'Dedicated Account Manager',
        'Maintenance Bulanan',
        'Priority Support 24/7',
      ],
      description: 'Untuk brand besar dengan kebutuhan custom dan integrasi lanjutan.',
      popular: false,
    },
  ],
  'jasa-pembuatan-website-sekolah': [
    {
      name: 'Paket Basic',
      price: 'Rp 500.000',
      features: [
        '5 Halaman (Profil, Visi Misi, Guru, Galeri, Kontak)',
        'Desain Responsif',
        'Gratis Domain .sch.id',
        'Hosting 1 Tahun',
        'SSL Certificate',
        'Form Kontak',
        '1x Revisi',
      ],
      description: 'Cocok untuk sekolah kecil yang butuh kehadiran online resmi.',
      popular: false,
    },
    {
      name: 'Paket Lengkap',
      price: 'Rp 1.500.000',
      features: [
        '10+ Halaman Custom',
        'PPDB Online',
        'Berita & Pengumuman',
        'Galeri Kegiatan',
        'Profil Guru & Staff',
        'Kalender Akademik',
        'Gratis Domain .sch.id',
        'Hosting & SSL',
        'Dashboard Admin',
        '3x Revisi',
        'Pelatihan Operator',
      ],
      description: 'Untuk sekolah yang butuh portal lengkap dengan PPDB online.',
      popular: true,
    },
    {
      name: 'Paket Custom',
      price: 'Hubungi Kami',
      features: [
        'Semua Fitur Paket Lengkap',
        'E-Learning / LMS',
        'Sistem Nilai Online',
        'Portal Orang Tua',
        'Absensi Digital',
        'Integrasi Dapodik',
        'Custom Branding',
        'Support Prioritas',
      ],
      description: 'Untuk sekolah besar dengan kebutuhan sistem akademik terintegrasi.',
      popular: false,
    },
  ],
  'jasa-pembuatan-website-travel': [
    {
      name: 'Paket Standard',
      price: 'Rp 1.500.000',
      features: [
        'Katalog Paket Wisata',
        'Form Booking via WhatsApp',
        'Galeri Destinasi',
        'Desain Modern & Responsif',
        'Gratis Domain .com & Hosting',
        'SSL Certificate',
        'SEO On-Page',
        'Google Maps',
        '2x Revisi',
      ],
      description: 'Cocok untuk agen travel kecil yang ingin tampil online profesional.',
      popular: false,
    },
    {
      name: 'Paket Premium',
      price: 'Rp 3.500.000',
      features: [
        'Sistem Booking Multi-Step',
        'E-Tiket Digital QR Code',
        'Notifikasi WhatsApp Otomatis',
        'Admin Dashboard Lengkap',
        'Blog Editor',
        'Sistem Kode Promo',
        'Gratis Domain & Hosting',
        'SEO Advanced + Schema',
        'Integrasi Payment Gateway',
        '5x Revisi',
      ],
      description: 'Website travel lengkap dengan booking system dan e-tiket digital.',
      popular: true,
    },
    {
      name: 'Paket Custom',
      price: 'Hubungi Kami',
      features: [
        'Semua Fitur Premium',
        'Multi-Bahasa',
        'Integrasi API Maskapai',
        'Sistem Affiliasi',
        'Payment Gateway Otomatis',
        'Custom Development',
        'Maintenance Bulanan',
        'Priority Support',
      ],
      description: 'Untuk tour operator besar dengan kebutuhan integrasi khusus.',
      popular: false,
    },
  ],
  'jasa-pembuatan-website-klinik': [
    {
      name: 'Paket Basic',
      price: 'Rp 1.250.000',
      features: [
        'Profil Klinik & Layanan',
        'Jadwal Dokter',
        'Form Reservasi via WhatsApp',
        'Galeri Klinik',
        'Gratis Domain & Hosting',
        'SSL Certificate',
        'Mobile Responsive',
        'SEO Basic',
        '2x Revisi',
      ],
      description: 'Cocok untuk praktik dokter dan klinik kecil.',
      popular: false,
    },
    {
      name: 'Paket Professional',
      price: 'Rp 2.500.000',
      features: [
        'Semua Fitur Basic',
        'Booking Janji Temu Online',
        'Notifikasi WhatsApp Pasien',
        'Blog Kesehatan',
        'Profil Dokter Lengkap',
        'Testimoni Pasien',
        'Dashboard Admin',
        'SEO + Schema Medis',
        '3x Revisi',
        'Pelatihan Staff',
      ],
      description: 'Untuk klinik yang butuh sistem booking online dan tampil profesional.',
      popular: true,
    },
    {
      name: 'Paket Custom',
      price: 'Hubungi Kami',
      features: [
        'Semua Fitur Professional',
        'Rekam Medis Digital',
        'Multi-Cabang',
        'Integrasi Lab',
        'Portal Pasien',
        'Custom Development',
        'Priority Support',
      ],
      description: 'Untuk rumah sakit dan klinik besar dengan kebutuhan sistem terintegrasi.',
      popular: false,
    },
  ],
}
